server:
  host: 0.0.0.0
  port: 8080

grpc:
  port: 9090

db:
  uri: jdbc:postgresql://postgres:5432/kotlinvertx
  user: username
  password: password

aws:
  sqs:
    emulator:
      enabled: true
      address: goaws:4100
