server:
  host: 0.0.0.0
  port: 8080

grpc:
  port: 9090

gcp:
  projectId: local-run
  pubsub:
    emulator:
      enabled: true
      address: gcp-pubsub:8538
  firestore:
    emulator:
      enabled: true
      address: firestore:8200

testdata:
  upload: true
