server:
  host: 0.0.0.0
  port: 8080

grpc:
  port: 9090

gcp:
  project: local-run
  firestore:
    emulator:
      enabled: true
      address: localhost:8200
  pubsub:
    emulator:
      enabled: true
      address: localhost:8538
