server:
  host: 0.0.0.0
  port: 8080

grpc:
  port: 9090

db:
  uri: jdbc:postgresql://localhost:5432/kotlinvertx
  user: username
  password: password

rabbitmq:
  uri: amqp://username:password@localhost:5672
