version: '3.9'

services:
  firestore:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=local-run
      - PORT=8200
    ports:
      - "127.0.0.1:8200:8200"

  gcp-pubsub:
    image: bigtruedata/gcloud-pubsub-emulator:latest
    command: start --host-port 0.0.0.0:8538
    ports:
      - "127.0.0.1:8538:8538"
