version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: kotlinvertx
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d kotlinvertx"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  migrate-db-schema:
    image: liquibase/liquibase:4.2
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./schema/:/liquibase/changelog:ro
    command: >
      ./liquibase --url="jdbc:postgresql://postgres:5432/kotlinvertx" --changeLogFile=changelog/changelog.xml --username=username --password=password update

  import-test-data:
    image: postgres:12
    user: root
    depends_on:
      migrate-db-schema:
        condition: service_completed_successfully
    volumes:
      - ./testdata/:/mnt/testdata/:ro
    command: >
      /bin/bash -c "
        for f in /mnt/testdata/*.sql; do
          PGPASSWORD=password psql -h postgres -p 5432 -d kotlinvertx -U username -f "$$f"
        done
      "
