version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: kotlinvertx
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d kotlinvertx"]
      interval: 5s
      timeout: 5s
      retries: 5

  goaws:
    image: pafortin/goaws:latest
    ports:
      - "127.0.0.1:4100:4100"
