secret:
  name: secrets

images:
  pullPolicy: IfNotPresent

gcp:
  projectId: default-project

  firestore:
    name: firestore
    image: mtlynch/firestore-emulator
    port: 8200

  pubsub:
    name: pubsub
    image: bigtruedata/gcloud-pubsub-emulator:latest
    port: 8538
