secret:
  name: secrets

images:
  pullPolicy: IfNotPresent

postgres:
  name: postgres
  image: postgres:12

  port: 5432

  username: username
  password: password
  dbname: kotlinvertx

  volume:
    name: postgres-volume
    claimName: postgres-volume-claim
    size: 100Mi
    path: "/var/lib/kotlin-vertx/dev-env/postgres-volume"

gcp:
  projectId: default-project

  pubsub:
    name: pubsub
    image: bigtruedata/gcloud-pubsub-emulator:latest
    port: 8538
