apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    server:
      host: 0.0.0.0
      port: {{ .Values.app.port }}
      security:
        headers: {{ if eq .Values.ingress.class "nginx" }}false{{ else }}true{{ end }}
    db:
      pool:
        size: {{ .Values.app.config.db.pool.size }}
        timeouts:
          connect: {{ .Values.app.config.db.pool.timeouts.connect }}
          idle: {{ .Values.app.config.db.pool.timeouts.idle }}
        cleaner: {{ .Values.app.config.db.pool.cleaner }}
