kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.configMap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    server:
      host: 0.0.0.0
      port: {{ .Values.app.port }}
      instances: {{ .Values.app.config.server.instances }}
      endpoints:
        health: {{ .Values.app.health.endpoint }}
        metrics: {{ .Values.app.metrics.endpoint }}
    db:
      pool:
        size: {{ .Values.app.config.db.pool.size }}
