{{ if eq .Values.ingress.class "gce" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.ingress.frontendConfig }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  redirectToHttps:
    enabled: {{ .Values.ingress.useHttps }}
{{ end }}
