apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: "{{ .Values.app.config.environmentName }}-ingress"
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.ingress.useHttps }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- end }}
spec:
  {{- if .Values.ingress.useHttps }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsCertName }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.port }}
      {{- if (eq .Values.ingress.useHttps true) }}
      host: {{ .Values.ingress.hostname }}
      {{- end }}
