apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app.pdb.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.app.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
