apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "{{ .Values.app.port }}"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.app.port }}
  type: ClusterIP
