app:
  name: kotlin-vertx
  version: latest
  imageName: mkorman/kotlin-vertx
  port: 8080
  historicRevisions: 3

  configMap: kotlin-vertx-config
  secrets: kotlin-vertx-secrets
  ingress:
    config: kotlin-vertx-ingress-backend-config

  config:
    environmentName: default
    db:
      pool:
        size: 8
        timeouts:
          connect: 30000
          idle: 0
        cleaner: 1000
    graylog:
      enabled: false
      host: graylog.monitoring.svc.cluster.local
      port: 12201

  health:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 20
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5

  autoscaling:
    name: kotlin-vertx-hpa

    min: 1
    max: 3

    targetMetrics:
      cpu: 85

  resources:
    cpu:
      request: 300m
      limit: 1
    memory:
      request: 512Mi
      limit: 2Gi

gitlab:
  project: ""
  environment: ""

images:
  pullPolicy: IfNotPresent
  pullSecret: ""

ingress:
  name: ingress
  hostname: localhost

  class: nginx
  frontendConfig: ingress-frontend-config

  useHttps: false
  tlsCertName: ""
  strictHostCheck: false

  proxyReadTimeout: 3600
  proxySendTimeout: 3600
