app:
  name: kotlin-vertx
  version: latest
  imageName: mkorman/kotlin-vertx
  port: 8080
  historicRevisions: 3
  environment: default

  configMap: config
  secrets: secrets

  config:
    db:
      pool:
        size: 8
        timeouts:
          connect: 30000
          idle: 0
        cleaner: 1000
    graylog:
      enabled: false
      host: graylog.monitoring.svc.cluster.local
      port: 12201

  health:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 20
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5

  autoscaling:
    name: app-hpa

    min: 1
    default: 1
    max: 3

    targetMetrics:
      cpu: 85

  resources:
    memory:
      request: 512Mi
      limit: 2Gi

gitlab:
  project: ""
  environment: ""

images:
  pullPolicy: IfNotPresent
  pullSecret: ""

ingress:
  name: ingress
  hostname: localhost

  useHttps: false
  tlsCertName: ""
  strictHostCheck: false

  proxyReadTimeout: 3600
  proxySendTimeout: 3600
