app:
  name: kotlin-vertx
  version: latest
  imageName: mkorman/kotlin-vertx
  port: 8080
  historicRevisions: 3

  env: kotlin-vertx-env

  config:
    environmentName: default
    profile: dev
    db:
      pool:
        size: 8
        timeouts:
          connect: 30000
          idle: 0
        cleaner: 1000
    graylog:
      enabled: false
      host: graylog.monitoring.svc.cluster.local
      port: 12201

  health:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 20
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5

  autoscaling:
    name: kotlin-vertx-hpa

    min: 1
    max: 3

    targetMetrics:
      cpu: 85

  resources:
    cpu:
      request: 1000m
    memory:
      request: 512Mi
      limit: 2Gi

  pdb:
    name: kotlin-vertx-pdb
    minAvailable: 1

gitlab:
  project: ""
  environment: ""

images:
  pullPolicy: IfNotPresent
  pullSecret: ""

ingress:
  name: kotlin-vertx-ingress
  hostname: localhost
  tlsCertArn: ""
