apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gcp.firestore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gcp.firestore.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gcp.firestore.name }}
    spec:
      containers:
        - name: {{ .Values.gcp.firestore.name }}
          image: {{ .Values.gcp.firestore.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gcp.firestore.port }}
              protocol: TCP
          env:
            - name: FIRESTORE_PROJECT_ID
              value: {{ .Values.gcp.projectId }}
            - name: PORT
              value: {{ .Values.gcp.firestore.port | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gcp.pubsub.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gcp.pubsub.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gcp.pubsub.name }}
    spec:
      containers:
        - name: {{ .Values.gcp.pubsub.name }}
          image: {{ .Values.gcp.pubsub.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gcp.pubsub.port }}
              protocol: TCP
          command:
            - /usr/bin/gcloud
            - beta
            - emulators
            - pubsub
            - start
            - --host-port=0.0.0.0:{{ .Values.gcp.pubsub.port }}
