apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbname }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.volume.claimName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pubsub.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pubsub.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pubsub.name }}
    spec:
      containers:
        - name: {{ .Values.pubsub.name }}
          image: {{ .Values.pubsub.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.pubsub.port }}
              protocol: TCP
          command:
            - /usr/bin/gcloud
            - beta
            - emulators
            - pubsub
            - start
            - --host-port=0.0.0.0:{{ .Values.pubsub.port }}
