{{- define "secrets" }}
gcp:
  project: {{ .Values.gcp.projectId }}

  firestore:
    emulator:
      enabled: true
      address: { { printf "%s.%s.svc.cluster.local:%d"
        .Values.gcp.firestore.name .Release.Namespace (.Values.gcp.firestore.port | int) } }

  pubsub:
    emulator:
      enabled: true
      address: {{ printf "%s.%s.svc.cluster.local:%d"
                  .Values.gcp.pubsub.name .Release.Namespace (.Values.gcp.pubsub.port | int) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/Opaque
data:
  secrets.yml: {{ include "secrets" . | b64enc | quote }}
  credentials.json: {{ printf "{}" | b64enc | quote }}
