{{- define "secrets" }}
db:
  uri: {{ printf "jdbc:postgresql://%s.%s.svc.cluster.local:%d/%s"
    .Values.postgres.name .Release.Namespace (.Values.postgres.port | int) .Values.postgres.dbname }}
  user: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
gcp:
  credentials:
    path: /app/credentials.json
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/Opaque
data:
  secrets.yml: {{ include "secrets" . | b64enc | quote }}
  credentials.json: {{ printf "{}" | b64enc | quote }}
