{{- define "secrets" }}
db:
  uri: {{ printf "jdbc:postgresql://%s.%s.svc.cluster.local:%d/%s"
    .Values.postgres.name .Release.Namespace (.Values.postgres.port | int) .Values.postgres.dbname }}
  user: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
gcp:
  project: {{ .Values.gcp.projectId }}
  pubsub:
    emulator:
      enabled: true
      address: {{ printf "%s.%s.svc.cluster.local:%d"
                  .Values.gcp.pubsub.name .Release.Namespace (.Values.gcp.pubsub.port | int) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/Opaque
data:
  secrets.yml: {{ include "secrets" . | b64enc | quote }}
  credentials.json: {{ printf "{}" | b64enc | quote }}
