apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gcp.pubsub.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.gcp.pubsub.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.gcp.pubsub.port }}
  type: ClusterIP
