apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.volume.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.volume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: {{ .Values.postgres.volume.path | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volume.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.volume.size }}
